module.exports = {
  timezone: "Europe/London",
  autoRole: "Player",

  staffRoles: ["Founder", "Admin", "Head Moderator", "Moderator", "Trial Moderator"],

  roles: {
    streamPing: "Stream"
  },

  channels: {
    support: "support",
    applications: "staff-application",
    logs: "🤖┃bot-logs",
    securityLogs: "🤖┃bot-logs",
    moderationLogs: "🤖┃bot-logs",
    messageLogs: "🤖┃bot-logs",
    memberLogs: "🤖┃bot-logs",
    transcripts: "ticket-transcripts",
    giveaways: "🎂┃giveaways",
    streams: "📡┃stream-alerts",
    posts: "🎥┃posts",
    landing: "🛬┃landing",
    takeoff: "🛫┃takeoff",
    rules: "🏫┃rules",
    chat: "💬┃chat"
  },

  categories: {
    tickets: "tickets"
  },

  rules: [
    "Be respectful to everyone.",
    "No racism, harassment, hate speech, or threats.",
    "No NSFW content.",
    "No scam links, phishing, or malicious files.",
    "No advertising other servers without permission.",
    "Do not spam messages, emojis, mentions, or reactions.",
    "Use channels for their proper purpose.",
    "Do not impersonate staff or other members.",
    "Do not evade punishments.",
    "Staff decisions are final."
  ],

  automod: {
    enabled: true,
    whitelistRoles: ["Founder"],
    whitelistChannels: [],
    whitelistUserIds: [],
    blockedWords: [
      "discord.gg/",
      "discord.com/invite/",
      "gg/",
      "nigg",
      "faggot",
      "kys"
    ],
    blockedTerms: [],
    suspiciousLinkPatterns: [
      "grabify",
      "iplogger",
      "bit.ly",
      "tinyurl",
      "t.ly",
      "goo.gl"
    ],
    antiInvite: true,
    antiPhishing: true,
    maxMentions: 5,
    capsThreshold: 0.72,
    capsMinLetters: 12,
    maxEmoji: 10,
    maxLineBreaks: 10,
    maxChars: 1200,
    charFloodRepeat: 20,
    maxZalgoMarks: 10,
    spamWindowMs: 6000,
    spamLimit: 6,
    repeatWindowMs: 8000,
    repeatLimit: 3,
    duplicateWindowMs: 20000,
    duplicateLimit: 4,
    repeatedLinkLimit: 3,
    repeatedAttachmentLimit: 3,
    timeoutThreshold: 2,
    timeoutMs: 10 * 60 * 1000,
    severeTimeoutThreshold: 4,
    severeTimeoutMs: 60 * 60 * 1000,
    kickThreshold: 6,
    banThreshold: 8,
    allowKick: false,
    allowBan: false,
    capsBypassRoles: ["Founder"],
    antiRaid: {
      enabled: true,
      windowMs: 15000,
      joinLimit: 8,
      action: "log",
      slowmodeSeconds: 10
    },
    minMessageLengthForAggressiveChecks: 6,
    context: {
      safeChannels: [],
      strictChannels: []
    },
    adaptive: {
      enabled: true,
      maxRiskTightening: 3
    },
    escalationLadder: [
      { minSeverity: 1, action: "warn" },
      { minSeverity: 3, action: "delete" },
      { minSeverity: 5, action: "timeout", durationMs: 10 * 60 * 1000 },
      { minSeverity: 7, action: "timeout", durationMs: 60 * 60 * 1000 },
      { minSeverity: 9, action: "kick", requireFlag: "allowKick" },
      { minSeverity: 10, action: "ban", requireFlag: "allowBan" }
    ]
  },

  antinuke: {
    threshold: 3,
    windowMs: 30000,
    punishmentTimeoutMs: 7 * 24 * 60 * 60 * 1000,
    trustedUserIds: [],
    actionThresholds: {
      channelDelete: { threshold: 2, windowMs: 20000 },
      channelCreate: { threshold: 6, windowMs: 20000 },
      roleDelete: { threshold: 2, windowMs: 20000 },
      roleCreate: { threshold: 6, windowMs: 20000 },
      rolePermissionEscalation: { threshold: 2, windowMs: 30000 },
      webhookChange: { threshold: 3, windowMs: 20000 },
      memberBan: { threshold: 4, windowMs: 20000 },
      memberKick: { threshold: 5, windowMs: 20000 },
      memberTimeout: { threshold: 8, windowMs: 20000 },
      memberPrune: { threshold: 1, windowMs: 30000 },
      guildUpdate: { threshold: 3, windowMs: 30000 },
      botAdd: { threshold: 2, windowMs: 30000 }
    },
    emergency: {
      stripDangerousPermissions: true,
      panicLockdown: true,
      timeoutOffender: true,
      kickOffender: false,
      banOffender: false
    },
    protectedRoles: ["Founder", "Admin"],
    realtimeMonitorIntervalMs: 45000
  },

  social: {
    checkIntervalMs: 120000
  },

  backup: {
    maxStored: 20,
    schedulerEnabled: true,
    schedulerIntervalMs: 6 * 60 * 60 * 1000
  },

  riddle: {
    intervalMinutes: 30,
    riddles: [
      "What has keys but can't open locks?",
      "What gets wetter the more it dries?",
      "What has hands but cannot clap?",
      "The more you take, the more you leave behind. What am I?",
      "What can travel around the world while staying in one corner?",
      "What has one eye but cannot see?",
      "What is full of holes but still holds water?",
      "What comes once in a minute, twice in a moment, but never in a thousand years?",
      "What has a neck but no head?",
      "What has many teeth but cannot bite?",
      "What goes up but never comes down?",
      "What has one head, one foot, and four legs?",
      "What has words but never speaks?",
      "What kind of band never plays music?",
      "What has cities, but no houses; forests, but no trees; and water, but no fish?",
      "What can you catch, but not throw?",
      "What begins with T, ends with T, and has T in it?",
      "What belongs to you, but other people use it more than you do?",
      "What has an eye, but cannot see?",
      "What gets bigger the more you take away from it?",
      "What has 13 hearts, but no other organs?",
      "What has legs, but doesn’t walk?",
      "What can fill a room but takes up no space?",
      "What runs, but never walks?",
      "What breaks yet never falls, and what falls yet never breaks?",
      "What has to be broken before you can use it?",
      "I am tall when I am young, and short when I am old. What am I?",
      "What month of the year has 28 days?",
      "What is always in front of you but can't be seen?",
      "What can you break, even if you never pick it up or touch it?",
      "What goes up and down but doesn't move?",
      "A man who was outside in the rain without an umbrella or hat didn't get a single hair on his head wet. Why?",
      "What gets wet while drying?",
      "What can you keep after giving to someone?",
      "I shave every day, but my beard stays the same. What am I?",
      "You see me once in June, twice in November, and not at all in May. What am I?",
      "What can you hold in your left hand but not in your right?",
      "What is black when it's clean and white when it's dirty?",
      "What can you hear but not touch or see?",
      "What invention lets you look right through a wall?",
      "What goes through cities and fields, but never moves?",
      "What has many keys but can't open a single lock?",
      "What has a thumb and four fingers but is not alive?",
      "What has a head and a tail but no body?",
      "What kind of room has no doors or windows?",
      "What has four wheels and flies?",
      "What has one eye, one horn, and gives milk?",
      "What has words, but never speaks?",
      "What has lots of eyes, but cannot see?",
      "What has one eye but can't see?",
      "What has many needles but does not sew?",
      "What has many branches but no fruit, trunk, or leaves?",
      "What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?",
      "What can clap without hands?",
      "What can be cracked, made, told, and played?",
      "What has an end but no beginning, a home but no family, and a space without a room?",
      "What has no beginning, end, or middle?",
      "What comes down but never goes up?",
      "What can you catch but never throw?",
      "What has many teeth, but can't bite?",
      "What can travel all around the world without leaving its corner?",
      "What can fill a room but takes no space?",
      "What has one head, one foot, and four legs?",
      "What can be as big as an elephant but weighs nothing?",
      "What gets sharper the more you use it?",
      "What has hands but can't clap?",
      "What gets bigger when more is taken away?",
      "What has a ring but no finger?",
      "What has cities, but no houses?",
      "What has forests, but no trees?",
      "What has water, but no fish?",
      "What has a face and two hands but no arms or legs?",
      "What has an eye but cannot see anything at all?",
      "What has teeth but never eats?",
      "What has a neck but no head?",
      "What has legs but can't walk?",
      "What can run but never walks?",
      "What has one letter and starts with E and ends with E?",
      "What can be measured but has no length, width, or height?",
      "What can you serve but never eat?",
      "What can point in every direction but can't reach the destination by itself?",
      "What kind of coat is always wet when you put it on?",
      "What can go up a chimney down but can't go down a chimney up?",
      "What is easy to lift but hard to throw?",
      "What has a bottom at the top?",
      "What has many rings but no fingers?",
      "What has only two words but thousands of letters?",
      "What can move faster than any car but has no engine?",
      "What kind of tree can you carry in your hand?",
      "What can never be put in a saucepan?",
      "What starts with a P, ends with an E, and has thousands of letters?",
      "What has six faces but does not wear makeup, has twenty-one eyes but cannot see?",
      "What has one eye but cannot see and is used for sewing?",
      "What can be seen in water but never gets wet?",
      "What has no life but can die?",
      "What has a bank but no money?",
      "What comes once in a year, twice in a week, and never in a day?",
      "What is full of keys but can't open any doors?",
      "What has four fingers and a thumb but is not a hand?",
      "What can run but cannot walk and has a bed?",
      "What is so fragile that saying its name breaks it?",
      "What can you put between 7 and 8 so the result is greater than 7 but less than 8?",
      "What has one eye but can still cry?",
      "What can be made of water but if you put it into water it dies?",
      "What can never ask a question but is often answered?",
      "What can you never eat for breakfast?",
      "What can you always find in the middle of nowhere?",
      "What has many stories but no pages?",
      "What can jump higher than a building?",
      "What belongs to you but others use it more?",
      "What has no body and no nose but can still smell?",
      "What has no voice but can still tell you everything?",
      "Bonus Riddle 1: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 2: What can you shadows but never speak?",
      "Bonus Riddle 3: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 4: What gets secrets the more you burn?",
      "Bonus Riddle 5: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 6: What can roots through hide but never memory?",
      "Bonus Riddle 7: What has no keys, yet can still open?",
      "Bonus Riddle 8: What is always tracks but never swim?",
      "Bonus Riddle 9: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 10: What has stories but never grow?",
      "Bonus Riddle 11: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 12: What can you colors but never break?",
      "Bonus Riddle 13: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 14: What gets letters the more you sleep?",
      "Bonus Riddle 15: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 16: What can voices through fall but never winter?",
      "Bonus Riddle 17: What has no locks, yet can still rust?",
      "Bonus Riddle 18: What is always maps but never sink?",
      "Bonus Riddle 19: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 20: What has wings but never fly?",
      "Bonus Riddle 21: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 22: What can you shadows but never speak?",
      "Bonus Riddle 23: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 24: What gets secrets the more you burn?",
      "Bonus Riddle 25: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 26: What can roots through hide but never memory?",
      "Bonus Riddle 27: What has no keys, yet can still open?",
      "Bonus Riddle 28: What is always tracks but never swim?",
      "Bonus Riddle 29: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 30: What has stories but never grow?",
      "Bonus Riddle 31: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 32: What can you colors but never break?",
      "Bonus Riddle 33: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 34: What gets letters the more you sleep?",
      "Bonus Riddle 35: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 36: What can voices through fall but never winter?",
      "Bonus Riddle 37: What has no locks, yet can still rust?",
      "Bonus Riddle 38: What is always maps but never sink?",
      "Bonus Riddle 39: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 40: What has wings but never fly?",
      "Bonus Riddle 41: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 42: What can you shadows but never speak?",
      "Bonus Riddle 43: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 44: What gets secrets the more you burn?",
      "Bonus Riddle 45: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 46: What can roots through hide but never memory?",
      "Bonus Riddle 47: What has no keys, yet can still open?",
      "Bonus Riddle 48: What is always tracks but never swim?",
      "Bonus Riddle 49: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 50: What has stories but never grow?",
      "Bonus Riddle 51: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 52: What can you colors but never break?",
      "Bonus Riddle 53: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 54: What gets letters the more you sleep?",
      "Bonus Riddle 55: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 56: What can voices through fall but never winter?",
      "Bonus Riddle 57: What has no locks, yet can still rust?",
      "Bonus Riddle 58: What is always maps but never sink?",
      "Bonus Riddle 59: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 60: What has wings but never fly?",
      "Bonus Riddle 61: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 62: What can you shadows but never speak?",
      "Bonus Riddle 63: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 64: What gets secrets the more you burn?",
      "Bonus Riddle 65: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 66: What can roots through hide but never memory?",
      "Bonus Riddle 67: What has no keys, yet can still open?",
      "Bonus Riddle 68: What is always tracks but never swim?",
      "Bonus Riddle 69: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 70: What has stories but never grow?",
      "Bonus Riddle 71: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 72: What can you colors but never break?",
      "Bonus Riddle 73: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 74: What gets letters the more you sleep?",
      "Bonus Riddle 75: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 76: What can voices through fall but never winter?",
      "Bonus Riddle 77: What has no locks, yet can still rust?",
      "Bonus Riddle 78: What is always maps but never sink?",
      "Bonus Riddle 79: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 80: What has wings but never fly?",
      "Bonus Riddle 81: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 82: What can you shadows but never speak?",
      "Bonus Riddle 83: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 84: What gets secrets the more you burn?",
      "Bonus Riddle 85: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 86: What can roots through hide but never memory?",
      "Bonus Riddle 87: What has no keys, yet can still open?",
      "Bonus Riddle 88: What is always tracks but never swim?",
      "Bonus Riddle 89: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 90: What has stories but never grow?",
      "Bonus Riddle 91: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 92: What can you colors but never break?",
      "Bonus Riddle 93: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 94: What gets letters the more you sleep?",
      "Bonus Riddle 95: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 96: What can voices through fall but never winter?",
      "Bonus Riddle 97: What has no locks, yet can still rust?",
      "Bonus Riddle 98: What is always maps but never sink?",
      "Bonus Riddle 99: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 100: What has wings but never fly?",
      "Bonus Riddle 101: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 102: What can you shadows but never speak?",
      "Bonus Riddle 103: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 104: What gets secrets the more you burn?",
      "Bonus Riddle 105: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 106: What can roots through hide but never memory?",
      "Bonus Riddle 107: What has no keys, yet can still open?",
      "Bonus Riddle 108: What is always tracks but never swim?",
      "Bonus Riddle 109: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 110: What has stories but never grow?",
      "Bonus Riddle 111: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 112: What can you colors but never break?",
      "Bonus Riddle 113: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 114: What gets letters the more you sleep?",
      "Bonus Riddle 115: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 116: What can voices through fall but never winter?",
      "Bonus Riddle 117: What has no locks, yet can still rust?",
      "Bonus Riddle 118: What is always maps but never sink?",
      "Bonus Riddle 119: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 120: What has wings but never fly?",
      "Bonus Riddle 121: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 122: What can you shadows but never speak?",
      "Bonus Riddle 123: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 124: What gets secrets the more you burn?",
      "Bonus Riddle 125: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 126: What can roots through hide but never memory?",
      "Bonus Riddle 127: What has no keys, yet can still open?",
      "Bonus Riddle 128: What is always tracks but never swim?",
      "Bonus Riddle 129: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 130: What has stories but never grow?",
      "Bonus Riddle 131: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 132: What can you colors but never break?",
      "Bonus Riddle 133: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 134: What gets letters the more you sleep?",
      "Bonus Riddle 135: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 136: What can voices through fall but never winter?",
      "Bonus Riddle 137: What has no locks, yet can still rust?",
      "Bonus Riddle 138: What is always maps but never sink?",
      "Bonus Riddle 139: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 140: What has wings but never fly?",
      "Bonus Riddle 141: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 142: What can you shadows but never speak?",
      "Bonus Riddle 143: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 144: What gets secrets the more you burn?",
      "Bonus Riddle 145: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 146: What can roots through hide but never memory?",
      "Bonus Riddle 147: What has no keys, yet can still open?",
      "Bonus Riddle 148: What is always tracks but never swim?",
      "Bonus Riddle 149: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 150: What has stories but never grow?",
      "Bonus Riddle 151: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 152: What can you colors but never break?",
      "Bonus Riddle 153: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 154: What gets letters the more you sleep?",
      "Bonus Riddle 155: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 156: What can voices through fall but never winter?",
      "Bonus Riddle 157: What has no locks, yet can still rust?",
      "Bonus Riddle 158: What is always maps but never sink?",
      "Bonus Riddle 159: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 160: What has wings but never fly?",
      "Bonus Riddle 161: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 162: What can you shadows but never speak?",
      "Bonus Riddle 163: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 164: What gets secrets the more you burn?",
      "Bonus Riddle 165: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 166: What can roots through hide but never memory?",
      "Bonus Riddle 167: What has no keys, yet can still open?",
      "Bonus Riddle 168: What is always tracks but never swim?",
      "Bonus Riddle 169: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 170: What has stories but never grow?",
      "Bonus Riddle 171: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 172: What can you colors but never break?",
      "Bonus Riddle 173: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 174: What gets letters the more you sleep?",
      "Bonus Riddle 175: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 176: What can voices through fall but never winter?",
      "Bonus Riddle 177: What has no locks, yet can still rust?",
      "Bonus Riddle 178: What is always maps but never sink?",
      "Bonus Riddle 179: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 180: What has wings but never fly?",
      "Bonus Riddle 181: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 182: What can you shadows but never speak?",
      "Bonus Riddle 183: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 184: What gets secrets the more you burn?",
      "Bonus Riddle 185: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 186: What can roots through hide but never memory?",
      "Bonus Riddle 187: What has no keys, yet can still open?",
      "Bonus Riddle 188: What is always tracks but never swim?",
      "Bonus Riddle 189: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 190: What has stories but never grow?",
      "Bonus Riddle 191: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 192: What can you colors but never break?",
      "Bonus Riddle 193: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 194: What gets letters the more you sleep?",
      "Bonus Riddle 195: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 196: What can voices through fall but never winter?",
      "Bonus Riddle 197: What has no locks, yet can still rust?",
      "Bonus Riddle 198: What is always maps but never sink?",
      "Bonus Riddle 199: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 200: What has wings but never fly?",
      "Bonus Riddle 201: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 202: What can you shadows but never speak?",
      "Bonus Riddle 203: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 204: What gets secrets the more you burn?",
      "Bonus Riddle 205: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 206: What can roots through hide but never memory?",
      "Bonus Riddle 207: What has no keys, yet can still open?",
      "Bonus Riddle 208: What is always tracks but never swim?",
      "Bonus Riddle 209: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 210: What has stories but never grow?",
      "Bonus Riddle 211: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 212: What can you colors but never break?",
      "Bonus Riddle 213: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 214: What gets letters the more you sleep?",
      "Bonus Riddle 215: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 216: What can voices through fall but never winter?",
      "Bonus Riddle 217: What has no locks, yet can still rust?",
      "Bonus Riddle 218: What is always maps but never sink?",
      "Bonus Riddle 219: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 220: What has wings but never fly?",
      "Bonus Riddle 221: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 222: What can you shadows but never speak?",
      "Bonus Riddle 223: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 224: What gets secrets the more you burn?",
      "Bonus Riddle 225: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 226: What can roots through hide but never memory?",
      "Bonus Riddle 227: What has no keys, yet can still open?",
      "Bonus Riddle 228: What is always tracks but never swim?",
      "Bonus Riddle 229: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 230: What has stories but never grow?",
      "Bonus Riddle 231: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 232: What can you colors but never break?",
      "Bonus Riddle 233: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 234: What gets letters the more you sleep?",
      "Bonus Riddle 235: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 236: What can voices through fall but never winter?",
      "Bonus Riddle 237: What has no locks, yet can still rust?",
      "Bonus Riddle 238: What is always maps but never sink?",
      "Bonus Riddle 239: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 240: What has wings but never fly?",
      "Bonus Riddle 241: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 242: What can you shadows but never speak?",
      "Bonus Riddle 243: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 244: What gets secrets the more you burn?",
      "Bonus Riddle 245: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 246: What can roots through hide but never memory?",
      "Bonus Riddle 247: What has no keys, yet can still open?",
      "Bonus Riddle 248: What is always tracks but never swim?",
      "Bonus Riddle 249: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 250: What has stories but never grow?",
      "Bonus Riddle 251: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 252: What can you colors but never break?",
      "Bonus Riddle 253: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 254: What gets letters the more you sleep?",
      "Bonus Riddle 255: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 256: What can voices through fall but never winter?",
      "Bonus Riddle 257: What has no locks, yet can still rust?",
      "Bonus Riddle 258: What is always maps but never sink?",
      "Bonus Riddle 259: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 260: What has wings but never fly?",
      "Bonus Riddle 261: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 262: What can you shadows but never speak?",
      "Bonus Riddle 263: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 264: What gets secrets the more you burn?",
      "Bonus Riddle 265: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 266: What can roots through hide but never memory?",
      "Bonus Riddle 267: What has no keys, yet can still open?",
      "Bonus Riddle 268: What is always tracks but never swim?",
      "Bonus Riddle 269: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 270: What has stories but never grow?",
      "Bonus Riddle 271: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 272: What can you colors but never break?",
      "Bonus Riddle 273: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 274: What gets letters the more you sleep?",
      "Bonus Riddle 275: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 276: What can voices through fall but never winter?",
      "Bonus Riddle 277: What has no locks, yet can still rust?",
      "Bonus Riddle 278: What is always maps but never sink?",
      "Bonus Riddle 279: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 280: What has wings but never fly?",
      "Bonus Riddle 281: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 282: What can you shadows but never speak?",
      "Bonus Riddle 283: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 284: What gets secrets the more you burn?",
      "Bonus Riddle 285: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 286: What can roots through hide but never memory?",
      "Bonus Riddle 287: What has no keys, yet can still open?",
      "Bonus Riddle 288: What is always tracks but never swim?",
      "Bonus Riddle 289: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 290: What has stories but never grow?",
      "Bonus Riddle 291: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 292: What can you colors but never break?",
      "Bonus Riddle 293: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 294: What gets letters the more you sleep?",
      "Bonus Riddle 295: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 296: What can voices through fall but never winter?",
      "Bonus Riddle 297: What has no locks, yet can still rust?",
      "Bonus Riddle 298: What is always maps but never sink?",
      "Bonus Riddle 299: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 300: What has wings but never fly?",
      "Bonus Riddle 301: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 302: What can you shadows but never speak?",
      "Bonus Riddle 303: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 304: What gets secrets the more you burn?",
      "Bonus Riddle 305: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 306: What can roots through hide but never memory?",
      "Bonus Riddle 307: What has no keys, yet can still open?",
      "Bonus Riddle 308: What is always tracks but never swim?",
      "Bonus Riddle 309: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 310: What has stories but never grow?",
      "Bonus Riddle 311: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 312: What can you colors but never break?",
      "Bonus Riddle 313: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 314: What gets letters the more you sleep?",
      "Bonus Riddle 315: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 316: What can voices through fall but never winter?",
      "Bonus Riddle 317: What has no locks, yet can still rust?",
      "Bonus Riddle 318: What is always maps but never sink?",
      "Bonus Riddle 319: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 320: What has wings but never fly?",
      "Bonus Riddle 321: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 322: What can you shadows but never speak?",
      "Bonus Riddle 323: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 324: What gets secrets the more you burn?",
      "Bonus Riddle 325: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 326: What can roots through hide but never memory?",
      "Bonus Riddle 327: What has no keys, yet can still open?",
      "Bonus Riddle 328: What is always tracks but never swim?",
      "Bonus Riddle 329: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 330: What has stories but never grow?",
      "Bonus Riddle 331: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 332: What can you colors but never break?",
      "Bonus Riddle 333: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 334: What gets letters the more you sleep?",
      "Bonus Riddle 335: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 336: What can voices through fall but never winter?",
      "Bonus Riddle 337: What has no locks, yet can still rust?",
      "Bonus Riddle 338: What is always maps but never sink?",
      "Bonus Riddle 339: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 340: What has wings but never fly?",
      "Bonus Riddle 341: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 342: What can you shadows but never speak?",
      "Bonus Riddle 343: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 344: What gets secrets the more you burn?",
      "Bonus Riddle 345: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 346: What can roots through hide but never memory?",
      "Bonus Riddle 347: What has no keys, yet can still open?",
      "Bonus Riddle 348: What is always tracks but never swim?",
      "Bonus Riddle 349: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 350: What has stories but never grow?",
      "Bonus Riddle 351: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 352: What can you colors but never break?",
      "Bonus Riddle 353: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 354: What gets letters the more you sleep?",
      "Bonus Riddle 355: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 356: What can voices through fall but never winter?",
      "Bonus Riddle 357: What has no locks, yet can still rust?",
      "Bonus Riddle 358: What is always maps but never sink?",
      "Bonus Riddle 359: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 360: What has wings but never fly?",
      "Bonus Riddle 361: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 362: What can you shadows but never speak?",
      "Bonus Riddle 363: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 364: What gets secrets the more you burn?",
      "Bonus Riddle 365: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 366: What can roots through hide but never memory?",
      "Bonus Riddle 367: What has no keys, yet can still open?",
      "Bonus Riddle 368: What is always tracks but never swim?",
      "Bonus Riddle 369: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 370: What has stories but never grow?",
      "Bonus Riddle 371: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 372: What can you colors but never break?",
      "Bonus Riddle 373: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 374: What gets letters the more you sleep?",
      "Bonus Riddle 375: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 376: What can voices through fall but never winter?",
      "Bonus Riddle 377: What has no locks, yet can still rust?",
      "Bonus Riddle 378: What is always maps but never sink?",
      "Bonus Riddle 379: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 380: What has wings but never fly?",
      "Bonus Riddle 381: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 382: What can you shadows but never speak?",
      "Bonus Riddle 383: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 384: What gets secrets the more you burn?",
      "Bonus Riddle 385: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 386: What can roots through hide but never memory?",
      "Bonus Riddle 387: What has no keys, yet can still open?",
      "Bonus Riddle 388: What is always tracks but never swim?",
      "Bonus Riddle 389: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 390: What has stories but never grow?",
      "Bonus Riddle 391: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 392: What can you colors but never break?",
      "Bonus Riddle 393: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 394: What gets letters the more you sleep?",
      "Bonus Riddle 395: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 396: What can voices through fall but never winter?",
      "Bonus Riddle 397: What has no locks, yet can still rust?",
      "Bonus Riddle 398: What is always maps but never sink?",
      "Bonus Riddle 399: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 400: What has wings but never fly?",
      "Bonus Riddle 401: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 402: What can you shadows but never speak?",
      "Bonus Riddle 403: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 404: What gets secrets the more you burn?",
      "Bonus Riddle 405: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 406: What can roots through hide but never memory?",
      "Bonus Riddle 407: What has no keys, yet can still open?",
      "Bonus Riddle 408: What is always tracks but never swim?",
      "Bonus Riddle 409: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 410: What has stories but never grow?",
      "Bonus Riddle 411: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 412: What can you colors but never break?",
      "Bonus Riddle 413: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 414: What gets letters the more you sleep?",
      "Bonus Riddle 415: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 416: What can voices through fall but never winter?",
      "Bonus Riddle 417: What has no locks, yet can still rust?",
      "Bonus Riddle 418: What is always maps but never sink?",
      "Bonus Riddle 419: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 420: What has wings but never fly?",
      "Bonus Riddle 421: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 422: What can you shadows but never speak?",
      "Bonus Riddle 423: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 424: What gets secrets the more you burn?",
      "Bonus Riddle 425: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 426: What can roots through hide but never memory?",
      "Bonus Riddle 427: What has no keys, yet can still open?",
      "Bonus Riddle 428: What is always tracks but never swim?",
      "Bonus Riddle 429: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 430: What has stories but never grow?",
      "Bonus Riddle 431: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 432: What can you colors but never break?",
      "Bonus Riddle 433: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 434: What gets letters the more you sleep?",
      "Bonus Riddle 435: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 436: What can voices through fall but never winter?",
      "Bonus Riddle 437: What has no locks, yet can still rust?",
      "Bonus Riddle 438: What is always maps but never sink?",
      "Bonus Riddle 439: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 440: What has wings but never fly?",
      "Bonus Riddle 441: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 442: What can you shadows but never speak?",
      "Bonus Riddle 443: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 444: What gets secrets the more you burn?",
      "Bonus Riddle 445: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 446: What can roots through hide but never memory?",
      "Bonus Riddle 447: What has no keys, yet can still open?",
      "Bonus Riddle 448: What is always tracks but never swim?",
      "Bonus Riddle 449: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 450: What has stories but never grow?",
      "Bonus Riddle 451: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 452: What can you colors but never break?",
      "Bonus Riddle 453: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 454: What gets letters the more you sleep?",
      "Bonus Riddle 455: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 456: What can voices through fall but never winter?",
      "Bonus Riddle 457: What has no locks, yet can still rust?",
      "Bonus Riddle 458: What is always maps but never sink?",
      "Bonus Riddle 459: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 460: What has wings but never fly?",
      "Bonus Riddle 461: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 462: What can you shadows but never speak?",
      "Bonus Riddle 463: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 464: What gets secrets the more you burn?",
      "Bonus Riddle 465: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 466: What can roots through hide but never memory?",
      "Bonus Riddle 467: What has no keys, yet can still open?",
      "Bonus Riddle 468: What is always tracks but never swim?",
      "Bonus Riddle 469: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 470: What has stories but never grow?",
      "Bonus Riddle 471: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 472: What can you colors but never break?",
      "Bonus Riddle 473: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 474: What gets letters the more you sleep?",
      "Bonus Riddle 475: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 476: What can voices through fall but never winter?",
      "Bonus Riddle 477: What has no locks, yet can still rust?",
      "Bonus Riddle 478: What is always maps but never sink?",
      "Bonus Riddle 479: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 480: What has wings but never fly?",
      "Bonus Riddle 481: I am windows when I am shout, but thunder when I am battery. What am I?",
      "Bonus Riddle 482: What can you shadows but never speak?",
      "Bonus Riddle 483: What has echoes, run, and noon, but no feet?",
      "Bonus Riddle 484: What gets secrets the more you burn?",
      "Bonus Riddle 485: What comes once in rings, twice in drift, and never in thunder?",
      "Bonus Riddle 486: What can roots through hide but never memory?",
      "Bonus Riddle 487: What has no keys, yet can still open?",
      "Bonus Riddle 488: What is always tracks but never swim?",
      "Bonus Riddle 489: What can be corners, walk, and thunder, all in one day?",
      "Bonus Riddle 490: What has stories but never grow?",
      "Bonus Riddle 491: I am faces when I am freeze, but noon when I am color. What am I?",
      "Bonus Riddle 492: What can you colors but never break?",
      "Bonus Riddle 493: What has branches, rest, and thunder, but no clock?",
      "Bonus Riddle 494: What gets letters the more you sleep?",
      "Bonus Riddle 495: What comes once in paths, twice in blink, and never in noon?",
      "Bonus Riddle 496: What can voices through fall but never winter?",
      "Bonus Riddle 497: What has no locks, yet can still rust?",
      "Bonus Riddle 498: What is always maps but never sink?",
      "Bonus Riddle 499: What can be signals, turn, and noon, all in one day?",
      "Bonus Riddle 500: What has wings but never fly?"
    ]
  }
};
