module.exports = {
  timezone: "Europe/London",
  autoRole: "Player",

  staffRoles: ["Founder", "Admin", "Head Moderator", "Moderator", "Trial Moderator"],

  roles: {
    streamPing: "Stream"
  },

  channels: {
    support: "support",
    applications: "staff-application",
    logs: "🤖┃bot-logs",
    securityLogs: "🤖┃bot-logs",
    moderationLogs: "🤖┃bot-logs",
    messageLogs: "🤖┃bot-logs",
    memberLogs: "🤖┃bot-logs",
    transcripts: "ticket-transcripts",
    giveaways: "🎂┃giveaways",
    streams: "📡┃stream-alerts",
    posts: "🎥┃posts",
    landing: "🛬┃landing",
    takeoff: "🛫┃takeoff",
    rules: "🏫┃rules",
    chat: "💬┃chat"
  },

  categories: {
    tickets: "tickets"
  },

  rules: [
    "Be respectful to everyone.",
    "No racism, harassment, hate speech, or threats.",
    "No NSFW content.",
    "No scam links, phishing, or malicious files.",
    "No advertising other servers without permission.",
    "Do not spam messages, emojis, mentions, or reactions.",
    "Use channels for their proper purpose.",
    "Do not impersonate staff or other members.",
    "Do not evade punishments.",
    "Staff decisions are final."
  ],

  automod: {
    enabled: true,
    whitelistRoles: ["Founder"],
    whitelistChannels: [],
    whitelistUserIds: [],
    blockedWords: [
      "discord.gg/",
      "discord.com/invite/",
      "gg/",
      "nigg",
      "faggot",
      "kys"
    ],
    blockedTerms: [],
    suspiciousLinkPatterns: [
      "grabify",
      "iplogger",
      "bit.ly",
      "tinyurl",
      "t.ly",
      "goo.gl"
    ],
    antiInvite: true,
    antiPhishing: true,
    maxMentions: 5,
    capsThreshold: 0.72,
    capsMinLetters: 12,
    maxEmoji: 10,
    maxLineBreaks: 10,
    maxChars: 1200,
    charFloodRepeat: 20,
    maxZalgoMarks: 10,
    spamWindowMs: 6000,
    spamLimit: 6,
    repeatWindowMs: 8000,
    repeatLimit: 3,
    duplicateWindowMs: 20000,
    duplicateLimit: 4,
    repeatedLinkLimit: 3,
    repeatedAttachmentLimit: 3,
    timeoutThreshold: 2,
    timeoutMs: 10 * 60 * 1000,
    severeTimeoutThreshold: 4,
    severeTimeoutMs: 60 * 60 * 1000,
    kickThreshold: 6,
    banThreshold: 8,
    allowKick: false,
    allowBan: false,
    capsBypassRoles: ["Founder"],
    antiRaid: {
      enabled: true,
      windowMs: 15000,
      joinLimit: 8,
      action: "log",
      slowmodeSeconds: 10
    },
    minMessageLengthForAggressiveChecks: 6,
    context: {
      safeChannels: [],
      strictChannels: []
    },
    adaptive: {
      enabled: true,
      maxRiskTightening: 3
    },
    escalationLadder: [
      { minSeverity: 1, action: "warn" },
      { minSeverity: 3, action: "delete" },
      { minSeverity: 5, action: "timeout", durationMs: 10 * 60 * 1000 },
      { minSeverity: 7, action: "timeout", durationMs: 60 * 60 * 1000 },
      { minSeverity: 9, action: "kick", requireFlag: "allowKick" },
      { minSeverity: 10, action: "ban", requireFlag: "allowBan" }
    ]
  },

  antinuke: {
    threshold: 3,
    windowMs: 30000,
    punishmentTimeoutMs: 7 * 24 * 60 * 60 * 1000,
    trustedUserIds: [],
    actionThresholds: {
      channelDelete: { threshold: 2, windowMs: 20000 },
      channelCreate: { threshold: 6, windowMs: 20000 },
      roleDelete: { threshold: 2, windowMs: 20000 },
      roleCreate: { threshold: 6, windowMs: 20000 },
      rolePermissionEscalation: { threshold: 2, windowMs: 30000 },
      webhookChange: { threshold: 3, windowMs: 20000 },
      memberBan: { threshold: 4, windowMs: 20000 },
      memberKick: { threshold: 5, windowMs: 20000 },
      memberTimeout: { threshold: 8, windowMs: 20000 },
      memberPrune: { threshold: 1, windowMs: 30000 },
      guildUpdate: { threshold: 3, windowMs: 30000 },
      botAdd: { threshold: 2, windowMs: 30000 }
    },
    emergency: {
      stripDangerousPermissions: true,
      panicLockdown: true,
      timeoutOffender: true,
      kickOffender: false,
      banOffender: false
    },
    protectedRoles: ["Founder", "Admin"],
    realtimeMonitorIntervalMs: 45000
  },

  social: {
    checkIntervalMs: 120000
  },

  backup: {
    maxStored: 20,
    schedulerEnabled: true,
    schedulerIntervalMs: 6 * 60 * 60 * 1000
  },

  riddle: {
    intervalMinutes: 30,
    riddles: [
      "What has keys but can't open locks?",
      "What gets wetter the more it dries?",
      "What has hands but cannot clap?",
      "The more you take, the more you leave behind. What am I?",
      "What can travel around the world while staying in one corner?",
      "What has one eye but cannot see?",
      "What is full of holes but still holds water?",
      "What comes once in a minute, twice in a moment, but never in a thousand years?",
      "What has a neck but no head?",
      "What has many teeth but cannot bite?",
      "What goes up but never comes down?",
      "What has one head, one foot, and four legs?",
      "What has words but never speaks?",
      "What kind of band never plays music?",
      "What has cities, but no houses; forests, but no trees; and water, but no fish?",
      "What can you catch, but not throw?",
      "What begins with T, ends with T, and has T in it?",
      "What belongs to you, but other people use it more than you do?",
      "What has an eye, but cannot see?",
      "What gets bigger the more you take away from it?",
      "What has 13 hearts, but no other organs?",
      "What has legs, but doesn’t walk?",
      "What can fill a room but takes up no space?",
      "What runs, but never walks?",
      "What breaks yet never falls, and what falls yet never breaks?",
      "What has to be broken before you can use it?",
      "I am tall when I am young, and short when I am old. What am I?",
      "What month of the year has 28 days?",
      "What is always in front of you but can't be seen?",
      "What can you break, even if you never pick it up or touch it?",
      "What goes up and down but doesn't move?",
      "A man who was outside in the rain without an umbrella or hat didn't get a single hair on his head wet. Why?",
      "What gets wet while drying?",
      "What can you keep after giving to someone?",
      "I shave every day, but my beard stays the same. What am I?",
      "You see me once in June, twice in November, and not at all in May. What am I?",
      "What can you hold in your left hand but not in your right?",
      "What is black when it's clean and white when it's dirty?",
      "What can you hear but not touch or see?",
      "What invention lets you look right through a wall?",
      "What goes through cities and fields, but never moves?",
      "What has many keys but can't open a single lock?",
      "What has a thumb and four fingers but is not alive?",
      "What has a head and a tail but no body?",
      "What kind of room has no doors or windows?",
      "What has four wheels and flies?",
      "What has one eye, one horn, and gives milk?",
      "What has words, but never speaks?",
      "What has lots of eyes, but cannot see?",
      "What has one eye but can't see?",
      "What has many needles but does not sew?",
      "What has many branches but no fruit, trunk, or leaves?",
      "What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?",
      "What can clap without hands?",
      "What can be cracked, made, told, and played?",
      "What has an end but no beginning, a home but no family, and a space without a room?",
      "What has no beginning, end, or middle?",
      "What comes down but never goes up?",
      "What can you catch but never throw?",
      "What has many teeth, but can't bite?",
      "What can travel all around the world without leaving its corner?",
      "What can fill a room but takes no space?",
      "What has one head, one foot, and four legs?",
      "What can be as big as an elephant but weighs nothing?",
      "What gets sharper the more you use it?",
      "What has hands but can't clap?",
      "What gets bigger when more is taken away?",
      "What has a ring but no finger?",
      "What has cities, but no houses?",
      "What has forests, but no trees?",
      "What has water, but no fish?",
      "What has a face and two hands but no arms or legs?",
      "What has an eye but cannot see anything at all?",
      "What has teeth but never eats?",
      "What has a neck but no head?",
      "What has legs but can't walk?",
      "What can run but never walks?",
      "What has one letter and starts with E and ends with E?",
      "What can be measured but has no length, width, or height?",
      "What can you serve but never eat?",
      "What can point in every direction but can't reach the destination by itself?",
      "What kind of coat is always wet when you put it on?",
      "What can go up a chimney down but can't go down a chimney up?",
      "What is easy to lift but hard to throw?",
      "What has a bottom at the top?",
      "What has many rings but no fingers?",
      "What has only two words but thousands of letters?",
      "What can move faster than any car but has no engine?",
      "What kind of tree can you carry in your hand?",
      "What can never be put in a saucepan?",
      "What starts with a P, ends with an E, and has thousands of letters?",
      "What has six faces but does not wear makeup, has twenty-one eyes but cannot see?",
      "What has one eye but cannot see and is used for sewing?",
      "What can be seen in water but never gets wet?",
      "What has no life but can die?",
      "What has a bank but no money?",
      "What comes once in a year, twice in a week, and never in a day?",
      "What is full of keys but can't open any doors?",
      "What has four fingers and a thumb but is not a hand?",
      "What can run but cannot walk and has a bed?",
      "What is so fragile that saying its name breaks it?",
      "What can you put between 7 and 8 so the result is greater than 7 but less than 8?",
      "What has one eye but can still cry?",
      "What can be made of water but if you put it into water it dies?",
      "What can never ask a question but is often answered?",
      "What can you never eat for breakfast?",
      "What can you always find in the middle of nowhere?",
      "What has many stories but no pages?",
      "What can jump higher than a building?",
      "What belongs to you but others use it more?",
      "What has no body and no nose but can still smell?",
      "What has no voice but can still tell you everything?"
    ]
  }
};
